/// Events generated by the timer system.
#[derive(Debug)]
pub enum TimerEvent {
    /// Generated every second to indicate a tick has occurred.
    Tick,
    /// Generated when the timer is stopped.
    StopTimer,
}
